In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds
import os

# 加載 Speech Commands 數據集
dataset_name = "speech_commands"
data_splits = ['train', 'test', 'validation']

# 下載數據集
datasets, dataset_info = tfds.load(
    dataset_name,
    split=data_splits,
    data_dir=os.path.join(os.getenv('HOME'), 'data'),
    # as_supervised=True,  # 返回 (audio, label) 形式的資料
    with_info=True  # 包含數據集的附加信息
)

train_dataset, test_dataset, validation_dataset = datasets

# 查看數據集的基本信息
print()
print()
print()
print()
print(f"Dataset: {dataset_name}")
print(f"Features: {dataset_info.features}")
print(f"Train samples: {len(list(train_dataset))}")
print(f"Validation samples: {len(list(validation_dataset))}")
print(f"Test samples: {len(list(test_dataset))}")
print(f"Labels: {dataset_info.features['label'].names}")

2024-12-13 16:54:41.195961: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1734080081.212930  610550 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1734080081.217714  610550 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-13 16:54:41.234818: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0000 00:00:1734080083.354778  610550 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0





Dataset: speech_commands
Features: FeaturesDict({
    'audio': Audio(shape=(None,), dtype=int16),
    'label': ClassLabel(shape=(), dtype=int64, num_classes=12),
})


2024-12-13 16:54:55.598405: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


Train samples: 85511


2024-12-13 16:54:57.233550: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


Validation samples: 10102
Test samples: 4890
Labels: ['down', 'go', 'left', 'no', 'off', 'on', 'right', 'stop', 'up', 'yes', '_silence_', '_unknown_']


In [7]:
dataset_info.features['audio'].__dict__

{'_file_format': 'wav',
 '_sample_rate': 16000,
 '_lazy_decode': False,
 '_doc': Documentation(desc=None, value_range=None),
 '_shape': (None,),
 '_dtype': numpy.int16,
 '_serialized_dtype': numpy.int16,
 '_serialized_shape': (None,),
 '_encoding': <Encoding.NONE: 'none'>,
 '_encoded_to_bytes': False,
 '_dynamic_shape': False,
 '_minimum': None,
 '_maximum': None,
 '_optional': False,
 '_audio_decoder': <tensorflow_datasets.core.features.audio_feature._EagerDecoder at 0x7e776487bdd0>,
 'np_dtype': numpy.int16,
 'tf_dtype': tf.int16}

In [3]:
# 打印採樣率
sample_rate = dataset_info.features['audio'].sample_rate
print(f"採樣率: {sample_rate} Hz")

採樣率: 16000 Hz


In [2]:
print(train_dataset.element_spec)

{'audio': TensorSpec(shape=(None,), dtype=tf.int16, name=None), 'label': TensorSpec(shape=(), dtype=tf.int64, name=None)}


In [14]:
_ = iter(train_dataset).next()
_

{'audio': <tf.Tensor: shape=(16000,), dtype=int16, numpy=array([-15, -18, -12, ...,  16,  21,  25], dtype=int16)>,
 'label': <tf.Tensor: shape=(), dtype=int64, numpy=4>}

In [16]:
_['audio']

<tf.Tensor: shape=(16000,), dtype=int16, numpy=array([-15, -18, -12, ...,  16,  21,  25], dtype=int16)>

In [17]:
# import tensorflow as tf
import soundfile as sf

# 假設 audio_tensor 是從 train_dataset 中提取的音訊 Tensor
audio_tensor = _['audio']

# 將 Tensor 轉為 NumPy 陣列
audio_array = audio_tensor.numpy()

# 指定採樣率（speech_commands 默認為 16kHz）
sample_rate = 16000

# 保存為 WAV 文件
output_filename = "__test.wav"
sf.write(output_filename, audio_array, sample_rate)

print(f"音訊已保存到 {output_filename}")

音訊已保存到 __test.wav


In [18]:
from IPython.display import Audio

# 播放音訊
Audio(output_filename)